### ISSUE TITLE
When running serve, an error occurs with the error message:Cannot use 'inmport.meta' outside a module

### ISSUE THREAD

**Issue by a17612431418** [antfu/unplugin-vue-components#483]
### Describe the bug

When running serve, an error occurs with the error message:Cannot use 'inmport.meta' outside a module
![image](https://user-images.githubusercontent.com/88608237/183427714-862d2510-9c0a-46c3-9b16-d5c33967ec3f.png)

### Reproduction

When running serve, an error occurs with the error message:Cannot use 'inmport.meta' outside a module

### System Info

```Shell
npm run serve
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hqchqc** [comment]
I also encountered the same problem just now. It is normal after returning to version 0.22.0

**Comment by JackieCheung** [comment]
same issue~ already relegated to v0.22.0

**Comment by pablosebastianr** [comment]
y ahora qué rompieron ????

**Comment by tinawng** [comment]
Still present in 0.22.2
```js
C:\Users\Tina\work\Place\node_modules\unplugin-vue-components\dist\chunk-YPBVGE6A.js:110
var _require = typeof _chunkEZUCZHGVjs.__require === "undefined" ? _module.createRequire.call(void 0, import.meta.url) : _chunkEZUCZHGVjs.__require;
                                                                              
                               ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1049:15)
    at Module._compile (node:internal/modules/cjs/loader:1084:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)      
    at _require.extensions.<computed> [as .js] (file:///C:/Users/Tina/work/Place/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62910:17)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Tina\work\Place\node_modules\unplugin-vue-components\dist\vite.js:3:24)
    ```

**Comment by carlmjohnson** [comment]
I also upgraded to 0.22.2 and have the import.meta problem.

**Comment by rromanv** [comment]
v0.20.0 is the latest one that still works

**Comment by tinawng** [comment]
> v0.20.0 is the latest one that still works

0.21.2 works as well for me
