### ISSUE TITLE
vite run using v0.22.1 gives "Cannot use 'import.meta' outside a module"

### ISSUE THREAD

**Issue by rezelute** [antfu/unplugin-vue-components#484]
### Describe the bug

Hi,
When compiling the vite project after updating to v0.22.1 (v0.22.0 works fine), I am getting the following error:
```
SyntaxError: Cannot use 'import.meta' outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object._require.extensions.<computed> [as .js] (.../vite/dist/node/chunks/dep-71eb12cb.js:62910:17)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\...\unplugin-vue-components\dist\vite.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

The Vite version is: 3.0.4. Let me know if I can provide anything else to help debug.

### Reproduction

Use vite with v0.22.1

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.68 GB / 31.92 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YujiaCheng1996** [comment]
same error in 0.22.2 vite3.

`failed to load config from D:\...\vite.config.ts
error when starting dev server:
D:\...\node_modules\unplugin-vue-components\dist\chunk-YPBVGE6A.js:110
var _require = typeof _chunkEZUCZHGVjs.__require === "undefined" ? _module.createRequire.call(void 0, import.meta.url) : _chunkEZUCZHGVjs.__require;
                                                                                                             ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1049:15)
    at Module._compile (node:internal/modules/cjs/loader:1084:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at _require.extensions.<computed> [as .js] (file:///D:/.../node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62910:17)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\...\node_modules\unplugin-vue-components\dist\vite.js:3:24)`

**Comment by yanbowe** [comment]
same here

**Comment by savelifeme** [comment]
vite: ^2.7.2，
"unplugin-vue-components": "^0.22.2",

也同样报错

![image](https://user-images.githubusercontent.com/32872731/183548575-a8b9cf63-2db0-4ec6-ab0a-727450ae296f.png)

**Comment by JiatLn** [comment]
^0.21.2 is work

**Comment by atzcl** [comment]
No need to downgrade, you can temporarily add `"type": "module"` to package.json to fix the problem

**Comment by savelifeme** [comment]
> ^0.21.2

"unplugin-vue-components": "0.21.2",

真的管用啊哈哈哈，谢谢哈

![image](https://user-images.githubusercontent.com/32872731/183551136-294fff5c-8b39-46b2-adc2-9567269b2d6b.png)

**Comment by Tsuj100** [comment]
+1

**Comment by valcosmos** [comment]
@atzcl  Thank u so much, it does work.

**Comment by fonghehe** [comment]
same error，hope to resolve

**Comment by rezelute** [comment]
Thank you for the fix 🙏
